const CITIES = [
  { code: "MOW", city: "Москва", cityUz: "Moskva", country: "RU", flag: "🇷🇺", airport: "Шереметьево / Домодедово / Внуково", slug: "Moskva" },
  { code: "LED", city: "Санкт-Петербург", cityUz: "Sankt-Peterburg", country: "RU", flag: "🇷🇺", airport: "Пулково", slug: "Sankt-peterburg" },
  { code: "KZN", city: "Казань", cityUz: "Qozon", country: "RU", flag: "🇷🇺", airport: "Казань", slug: "Kazan" },
  { code: "SVX", city: "Екатеринбург", cityUz: "Yekaterinburg", country: "RU", flag: "🇷🇺", airport: "Кольцово", slug: "Ekaterinburg" },
  { code: "OVB", city: "Новосибирск", cityUz: "Novosibirsk", country: "RU", flag: "🇷🇺", airport: "Толмачёво", slug: "Novosibirsk" },
  { code: "KRR", city: "Краснодар", cityUz: "Krasnodar", country: "RU", flag: "🇷🇺", airport: "Пашковский", slug: "Krasnodar" },
  { code: "ROV", city: "Ростов-на-Дону", cityUz: "Rostov-na-Donu", country: "RU", flag: "🇷🇺", airport: "Платов", slug: "Rostov-na-donu" },
  { code: "UFA", city: "Уфа", cityUz: "Ufa", country: "RU", flag: "🇷🇺", airport: "Уфа", slug: "Ufa" },
  { code: "TAS", city: "Ташкент", cityUz: "Toshkent", country: "UZ", flag: "🇺🇿", airport: "Ташкент (Ислам Каримов)", slug: "Tashkent" },
  { code: "SKD", city: "Самарканд", cityUz: "Samarqand", country: "UZ", flag: "🇺🇿", airport: "Самарканд", slug: "Samarkand" },
  { code: "FEG", city: "Фергана", cityUz: "Farg'ona", country: "UZ", flag: "🇺🇿", airport: "Фергана", slug: "Fergana" },
  { code: "NMA", city: "Наманган", cityUz: "Namangan", country: "UZ", flag: "🇺🇿", airport: "Наманган", slug: "Namangan" },
  { code: "AZN", city: "Андижан", cityUz: "Andijon", country: "UZ", flag: "🇺🇿", airport: "Андижан", slug: "Andijan" },
  { code: "BHK", city: "Бухара", cityUz: "Buxoro", country: "UZ", flag: "🇺🇿", airport: "Бухара", slug: "Buhara" },
  { code: "UGC", city: "Ургенч", cityUz: "Urganch", country: "UZ", flag: "🇺🇿", airport: "Ургенч", slug: "Urgench" },
];

const ROUTES = [
  { from: "TAS", to: "MOW", date: "12 сен", dateUz: "12 sen", oldPrice: 24890, price: 18490, baggage: true, airline: "Uzbekistan Airways" },
  { from: "MOW", to: "TAS", date: "20 сен", dateUz: "20 sen", oldPrice: 21990, price: 16990, baggage: true, airline: "Аэрофлот" },
  { from: "SKD", to: "LED", date: "15 сен", dateUz: "15 sen", oldPrice: 27500, price: 21200, baggage: false, airline: "Uzbekistan Airways" },
  { from: "MOW", to: "SKD", date: "18 сен", dateUz: "18 sen", oldPrice: 23400, price: 17900, baggage: true, airline: "Уральские авиалинии" },
  { from: "FEG", to: "MOW", date: "10 сен", dateUz: "10 sen", oldPrice: 22100, price: 16700, baggage: false, airline: "Uzbekistan Airways" },
  { from: "MOW", to: "AZN", date: "22 сен", dateUz: "22 sen", oldPrice: 24300, price: 18200, baggage: true, airline: "Nordwind" },
  { from: "TAS", to: "KZN", date: "14 сен", dateUz: "14 sen", oldPrice: 19800, price: 14500, baggage: false, airline: "Uzbekistan Airways" },
  { from: "SVX", to: "TAS", date: "25 сен", dateUz: "25 sen", oldPrice: 20600, price: 15300, baggage: true, airline: "Уральские авиалинии" },
  { from: "BHK", to: "MOW", date: "11 сен", dateUz: "11 sen", oldPrice: 23700, price: 17400, baggage: true, airline: "Uzbekistan Airways" },
  { from: "OVB", to: "NMA", date: "28 сен", dateUz: "28 sen", oldPrice: 26900, price: 19900, baggage: false, airline: "Nordwind" },
];

const HOSTELS = [
  { city: "Москва", cityUz: "Moskva", name: "Bear Hostel Arbat", area: "м. Смоленская", areaUz: "Smolenskaya metrosi", rating: 4.6, reviews: 312, verified: true, price: 850 },
  { city: "Москва", cityUz: "Moskva", name: "Друзья на Тульской", area: "м. Тульская", areaUz: "Tulskaya metrosi", rating: 4.4, reviews: 178, verified: true, price: 750 },
  { city: "Москва", cityUz: "Moskva", name: "Hostel Chistye Prudy", area: "м. Чистые пруды", areaUz: "Chistye prudy metrosi", rating: 4.5, reviews: 264, verified: true, price: 900 },
  { city: "Санкт-Петербург", cityUz: "Sankt-Peterburg", name: "GoodMorning Hostel", area: "исторический центр", areaUz: "tarixiy markaz", rating: 4.7, reviews: 401, verified: true, price: 900 },
  { city: "Санкт-Петербург", cityUz: "Sankt-Peterburg", name: "Location Hostel", area: "м. Пл. Восстания", areaUz: "Vosstaniya metrosi", rating: 4.5, reviews: 156, verified: true, price: 800 },
  { city: "Санкт-Петербург", cityUz: "Sankt-Peterburg", name: "Sleep Cheap Hostel", area: "м. Технологический институт", areaUz: "Texnologicheskiy institut metrosi", rating: 4.3, reviews: 97, verified: true, price: 700 },
];

const USEFUL_INFO = [
  { icon: "📋", key: "registration", title: "Регистрация по месту пребывания", titleUz: "Turar joyda ro'yxatdan o'tish", text: "Как и где встать на учёт в течение 7 рабочих дней после въезда.", textUz: "Kelgandan keyin 7 ish kuni ichida qayerda va qanday ro'yxatdan o'tish kerak." },
  { icon: "🔑", key: "housing", title: "Как не попасться на обман с жильём", titleUz: "Uy-joy bilan aldanib qolmaslik", text: "Что проверить перед оплатой: отзывы, документы хозяина, предоплата без осмотра.", textUz: "To'lovdan oldin nimani tekshirish kerak: sharhlar, egasining hujjatlari, ko'rmasdan oldindan to'lov." },
  { icon: "📱", key: "sim", title: "SIM-карта", titleUz: "SIM-karta", text: "Какие операторы работают в России, что нужно для покупки номера — и как продержаться первые часы (в аэропорту Ташкента теперь продают временную SIM-карту на 10 минут активации).", textUz: "Rossiyada qaysi operatorlar ishlaydi, raqam sotib olish uchun nima kerak — va birinchi soatlarni qanday o'tkazish (Toshkent aeroportida endi 10 daqiqalik faollashtirish uchun vaqtinchalik SIM-karta sotiladi)." },
  { icon: "🪪", key: "patent", title: "Патент на работу", titleUz: "Ishlash uchun patent", text: "Как оформить разрешение для трудовой деятельности иностранному гражданину.", textUz: "Chet el fuqarosi uchun mehnat ruxsatnomasini qanday rasmiylashtirish mumkin." },
  { icon: "💼", key: "job", title: "Поиск работы", titleUz: "Ish qidirish", text: "Проверенные площадки и кадровые агентства, куда можно обратиться.", textUz: "Murojaat qilish mumkin bo'lgan tekshirilgan platformalar va kadr agentliklari." },
  { icon: "🏦", key: "bank", title: "Банковская карта", titleUz: "Bank kartasi", text: "Как открыть счёт и подключить карту для повседневных расходов.", textUz: "Kundalik xarajatlar uchun hisob ochish va karta ulash haqida." },
  { icon: "💱", key: "transfer", title: "Переводы: как не переплатить на курсе", titleUz: "O'tkazmalar: kursda ortiqcha to'lamaslik", text: "Курс у разных сервисов (банки, Золотая Корона и другие) отличается — сравнивайте перед переводом, а не берите первый попавшийся.", textUz: "Turli xizmatlarning (banklar, Zolotaya Korona va boshqalar) kursi farq qiladi — o'tkazishdan oldin solishtiring, birinchi uchragan xizmatni olmang." },
  { icon: "⚕️", key: "insurance", title: "Медицинская страховка (ДМС)", titleUz: "Tibbiy sug'urta", text: "Что нужно оформить перед выездом и как продлить полис на месте." , textUz: "Jo'nashdan oldin nimalarni rasmiylashtirish va joyida polisni qanday uzaytirish kerak."},
];

const TRANSLATIONS = {
  "nav.tickets":      { ru: "Авиабилеты",  uz: "Aviachiptalar" },
  "nav.hotels":       { ru: "Отели",       uz: "Mehmonxonalar" },
  "nav.trains":       { ru: "Поезда",      uz: "Poyezdlar" },
  "nav.support":      { ru: "Поддержка",   uz: "Yordam" },
  "hero.title":       { ru: "Летай на родину и обратно без лишних хлопот", uz: "Vatanga va orqaga hech qanday muammosiz uchib boring" },
  "hero.subtitle":    { ru: "Дешёвые авиабилеты между Узбекистаном и Россией — подбираем лучшие цены за вас", uz: "O‘zbekiston va Rossiya orasida arzon aviachiptalar — siz uchun eng yaxshi narxlarni topamiz" },
  "search.from":      { ru: "Откуда", uz: "Qayerdan" },
  "search.to":        { ru: "Куда", uz: "Qayerga" },
  "search.placeholder": { ru: "Город или аэропорт", uz: "Shahar yoki aeroport" },
  "search.oneway":    { ru: "В одну сторону", uz: "Bir tomonlama" },
  "search.roundtrip": { ru: "Туда-обратно", uz: "Borish-qaytish" },
  "search.date":      { ru: "Дата вылета", uz: "Uchish sanasi" },
  "search.dateBack":  { ru: "Дата обратно", uz: "Qaytish sanasi" },
  "search.passengers":{ ru: "Пассажиры", uz: "Yo‘lovchilar" },
  "search.class":     { ru: "Класс обслуживания", uz: "Xizmat sinfi" },
  "search.submit":    { ru: "Найти билеты", uz: "Chiptalarni qidirish" },
  "search.directOnly": { ru: "Только прямые рейсы", uz: "Faqat to‘g‘ridan-to‘g‘ri reyslar" },
  "trust.tickets":    { ru: "билетов куплено через Tutu в 2026 году", uz: "2026 yilda Tutu orqali sotib olingan chiptalar" },
  "trust.rating":     { ru: "средняя оценка сервиса", uz: "xizmatning o‘rtacha bahosi" },
  "trust.support":    { ru: "поддержка на русском языке", uz: "rus tilida qo‘llab-quvvatlash" },
  "routes.baggage":   { ru: "23 кг багажа включено", uz: "23 kg yuk narxga kiritilgan" },
  "class.economy":    { ru: "Эконом", uz: "Ekonom" },
  "class.comfort":    { ru: "Комфорт", uz: "Komfort" },
  "class.business":   { ru: "Бизнес", uz: "Biznes" },
  "passengers.label": { ru: "пассажир", uz: "yo‘lovchi" },
  "passengers.adults":{ ru: "Взрослые", uz: "Kattalar" },
  "passengers.adultsHint":   { ru: "от 12 лет", uz: "12 yoshdan" },
  "passengers.children":     { ru: "Дети", uz: "Bolalar" },
  "passengers.childrenHint": { ru: "от 2 до 11 лет", uz: "2 dan 11 yoshgacha" },
  "passengers.infants":      { ru: "Младенцы", uz: "Chaqaloqlar" },
  "passengers.infantsHint":  { ru: "до 2 лет, без места", uz: "2 yoshgacha, o‘rinsiz" },
  "route.approx":     { ru: "≈", uz: "≈" },
  "route.sum":        { ru: "сум", uz: "so‘m" },
  "routes.title":     { ru: "Популярные направления", uz: "Mashhur yo‘nalishlar" },
  "routes.subtitle":  { ru: "Билеты между Узбекистаном и Россией по выгодным ценам", uz: "O‘zbekiston va Rossiya orasida qulay narxlardagi chiptalar" },
  "routes.cta":       { ru: "Смотреть", uz: "Ko‘rish" },
  "hostels.title":    { ru: "Где остановиться", uz: "Qayerda to‘xtash mumkin" },
  "hostels.subtitle": { ru: "Проверенные хостелы рядом с метро в Москве и Санкт-Петербурге", uz: "Moskva va Sankt-Peterburgda metroga yaqin tekshirilgan хostellar" },
  "hostels.from":     { ru: "от", uz: "dan boshlab" },
  "hostels.night":    { ru: "ночь", uz: "kecha" },
  "hostels.reviews":  { ru: "оценок", uz: "baho" },
  "hostels.verified": { ru: "Проверено Tutu", uz: "Tutu tomonidan tekshirilgan" },
  "info.title":       { ru: "Полезно знать по приезде", uz: "Kelganingizda bilish foydali" },
  "info.subtitle":    { ru: "Чек-лист первых шагов в России", uz: "Rossiyadagi birinchi qadamlar cheklisti" },
  "promo.title":      { ru: "Не забудьте про билет домой", uz: "Uyga qaytish chiptasini unutmang" },
  "promo.subtitle":   { ru: "Если пока не знаете точную дату — оформите обратный билет позже и получите скидку 1000 ₽ по промокоду", uz: "Aniq sanani hali bilmasangiz — qaytish chiptasini keyinroq rasmiylashtiring va promokod bilan 1000 ₽ chegirma oling" },
  "promo.copy":       { ru: "Скопировать код", uz: "Kodni nusxalash" },
  "promo.copied":     { ru: "Скопировано ✓", uz: "Nusxalandi ✓" },
  "footer.payments":  { ru: "Принимаем к оплате", uz: "To‘lov usullari" },
  "footer.tickets":   { ru: "Авиабилеты", uz: "Aviachiptalar" },
  "footer.trains":    { ru: "Ж/д билеты", uz: "Temir yo'l chiptalari" },
  "footer.buses":     { ru: "Автобусы", uz: "Avtobuslar" },
  "footer.hotels":    { ru: "Отели", uz: "Mehmonxonalar" },
  "footer.insurance": { ru: "Страхование", uz: "Sug'urta" },
  "footer.visas":     { ru: "Визы", uz: "Vizalar" },
  "footer.about":     { ru: "О компании", uz: "Kompaniya haqida" },
  "footer.contacts":  { ru: "Контакты", uz: "Kontaktlar" },
  "footer.support24": { ru: "Поддержка 24/7", uz: "24/7 qo'llab-quvvatlash" },
  "footer.app":       { ru: "Приложение Tutu", uz: "Tutu ilovasi" },
  "footer.appStoreHint":    { ru: "Загрузите в", uz: "Yuklab oling" },
  "footer.googlePlayHint":  { ru: "Доступно в", uz: "Mavjud" },
  "footer.copyright": { ru: "© 2026 tutu.ru", uz: "© 2026 tutu.ru" },
  "footer.visaSupport": { ru: "Визовая поддержка 24/7:", uz: "24/7 viza yordami:" },
};

const PROMO_CODE = "DOMOY1000";

// Курс ЦБ на момент проверки: 1 ₽ ≈ 139 сум (сентябрь 2026, источник bank.uz). Обновляется вручную,
// в реальном продукте курс должен подтягиваться из актуального источника, а не быть константой.
const UZS_RATE = 139;
